# Generated by Django 3.2 on 2022-10-10 22:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='required, max_len: 150', max_length=150, unique=True, verbose_name='brand name')),
                ('description', models.TextField(blank=True, help_text='optional, max_len: 2000', max_length=2000, null=True, verbose_name='brand brief info')),
                ('logo', models.CharField(max_length=30, verbose_name='replace this to imagefield')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Producer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='required, max_len: 150', max_length=150, unique=True, verbose_name='manufacturer name')),
                ('description', models.TextField(blank=True, help_text='optional, max_len: 2000', max_length=2000, null=True, verbose_name='producer brief info')),
            ],
        ),
        migrations.CreateModel(
            name='ProductAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='required, max_len: 150', max_length=150, unique=True, verbose_name='product item attribute name')),
            ],
        ),
        migrations.CreateModel(
            name='ProductAttributeValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(help_text='required, max_length: 255', max_length=255, unique=True, verbose_name='attribute value')),
                ('attr', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='values', to='dbexample.productattribute')),
            ],
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='required, max_len: 100', max_length=100, unique=True, verbose_name='product category name')),
                ('slug', models.SlugField(help_text='required, allowed=[letters, numbers, hyphens, underscore], max_len: 150', max_length=150, unique=True, verbose_name='product category url')),
                ('is_active', models.BooleanField(default=True, help_text='optional, defalut: True', verbose_name='product category active status')),
            ],
            options={
                'verbose_name': 'Product category',
                'verbose_name_plural': 'Product categories',
            },
        ),
        migrations.CreateModel(
            name='ProductItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(help_text='required, max_len: 20', max_length=20, verbose_name='stock keeping unit')),
                ('regular_price', models.DecimalField(decimal_places=2, help_text='required, max_price: 9_999_999.99', max_digits=9, verbose_name='product item regular price')),
                ('discount_price', models.DecimalField(decimal_places=2, help_text='required, max_price: 9_999_999.99', max_digits=9, verbose_name='product item discount price')),
                ('is_active', models.BooleanField(default=False, help_text='bool; optional; default: False', verbose_name='product item status')),
                ('_view_count', models.PositiveIntegerField(default=0, help_text='required, starts with 0', verbose_name='number of views')),
                ('made_in', models.CharField(max_length=150, verbose_name='change this to country FK')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='format: Y-m-d H:M:S', verbose_name='product item creation time')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='format: Y-m-d H:M:S', verbose_name='product item last update time')),
            ],
        ),
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='required, max_len: 150', max_length=150, unique=True, verbose_name='type of product')),
                ('logo', models.CharField(max_length=30, verbose_name='replace this to imagefield')),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='required, max_len: 150', max_length=150, unique=True, verbose_name='name of the agent/partner')),
                ('address', models.CharField(max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit', models.CharField(help_text='required, max_len: 20', max_length=20, verbose_name='product unit')),
                ('initial_amount', models.PositiveIntegerField(default=0, help_text='required, default: 0', verbose_name='initial amount of product')),
                ('current_amount', models.PositiveIntegerField(default=0, help_text='required, default: 0', verbose_name='current amount of product')),
                ('items_sold', models.PositiveIntegerField(default=0, help_text='required, default: 0', verbose_name='amount of product sold')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='stock', to='dbexample.productitem')),
            ],
        ),
        migrations.CreateModel(
            name='ProductToAttributeLinkTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attr_values', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dbexample.productattributevalue')),
                ('product_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dbexample.productitem')),
            ],
        ),
        migrations.CreateModel(
            name='ProductSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('web_id', models.CharField(help_text='required, numbers', max_length=50, unique=True, verbose_name='product_set web id')),
                ('slug', models.SlugField(help_text='required, allowed=[letters, numbers, hyphens, underscore], max_len: 255', max_length=255, verbose_name='product_set url')),
                ('name', models.CharField(help_text='required, max_len: 150', max_length=150, verbose_name='product_set name')),
                ('description', models.TextField(help_text='required, max_len: 2000', max_length=2000, verbose_name='product_set description')),
                ('is_active', models.BooleanField(default=False, help_text='bool; optional; default: False', verbose_name='product_set status')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='format: Y-m-d H:M:S', verbose_name='product_set creation time')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='format: Y-m-d H:M:S', verbose_name='product_set last update time')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='productsets', to='dbexample.brand')),
                ('categories', models.ManyToManyField(related_name='productsets', to='dbexample.ProductCategory')),
                ('p_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='productsets', to='dbexample.producttype')),
            ],
        ),
        migrations.AddField(
            model_name='productitem',
            name='attrs',
            field=models.ManyToManyField(related_name='product_items', through='dbexample.ProductToAttributeLinkTable', to='dbexample.ProductAttributeValue'),
        ),
        migrations.AddField(
            model_name='productitem',
            name='product_set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='dbexample.productset'),
        ),
        migrations.AddField(
            model_name='brand',
            name='producer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='brands', to='dbexample.producer'),
        ),
        migrations.AddConstraint(
            model_name='producttoattributelinktable',
            constraint=models.UniqueConstraint(fields=('product_item', 'attr_values'), name='unique_product_attr'),
        ),
    ]
