# Generated by Django 3.2 on 2022-09-30 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbexample', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('web_id', models.CharField(help_text='required, numbers', max_length=50, unique=True, verbose_name='product_set web id')),
                ('slug', models.SlugField(help_text='required, allowed=[letters, numbers, hyphens, underscore], max_len: 255', max_length=255, verbose_name='product_set url')),
                ('name', models.CharField(help_text='required, max_len: 150', max_length=150, verbose_name='product_set name')),
                ('description', models.TextField(help_text='required, max_len: 2000', max_length=2000, verbose_name='product_set description')),
                ('is_active', models.BooleanField(default=False, help_text='bool; optional; default: False', verbose_name='product_set status')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='format: Y-m-d H:M:S', verbose_name='product_set creation time')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='format: Y-m-d H:M:S', verbose_name='product_set last update time')),
                ('category', models.ManyToManyField(to='dbexample.ProductCategory')),
            ],
        ),
    ]
